# Generated by Django 3.0.8 on 2020-07-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0002_team_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.User'),
        ),
    ]
