# Generated by Django 3.0.8 on 2020-07-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20200718_0515'),
        ('user', '0004_auto_20200718_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='team.Team'),
        ),
    ]
