# Generated by Django 3.0.8 on 2020-07-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
