# Generated by Django 3.0.8 on 2020-07-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20200717_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='date_of_inaugration',
            new_name='date_of_inauguration',
        ),
    ]
